FROM python:3.11
WORKDIR /app/backend
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ .
# For local development
#COPY .env .
#COPY config/ config/
EXPOSE 5000
CMD ["python", "app/main.py"]