FROM node:current-alpine as build
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm cache clean --force && \
    npm install
COPY frontend/ . 
RUN npm run build
 
FROM nginx:latest as production
WORKDIR /usr/share/nginx/html
COPY --from=build /app/frontend/dist /usr/share/nginx/html
# Optional: Customize Nginx configuration
#COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]