FROM python:3.11
RUN apt-get update && apt-get install -y nginx
WORKDIR /app/backend
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ .

#nginx
COPY config/nginx_backend.conf /etc/nginx/conf.d/default.conf

#cert
COPY config/stockspy.space_ssl_certificate.cer /etc/ssl/certs/stockspy.space_ssl_certificate.cer
COPY config/_.stockspy.space_private_key.key /etc/ssl/private/_.stockspy.space_private_key.key

EXPOSE 80 443
CMD service nginx start && python app/main.py