FROM node:current-alpine as build
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm cache clean --force && npm install
COPY frontend/ .
RUN npm run build
 
FROM nginx:latest as production
WORKDIR /usr/share/nginx/html
COPY --from=build /app/frontend/dist /usr/share/nginx/html

#nginx
COPY config/nginx_frontend.conf /etc/nginx/conf.d/default.conf

#cert
COPY config/stockspy.space_ssl_certificate.cer /etc/ssl/certs/stockspy.space_ssl_certificate.cer
COPY config/_.stockspy.space_private_key.key /etc/ssl/private/_.stockspy.space_private_key.key

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]